# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'WhooingCal' do
	use_frameworks!
	pod 'AsyncSwift'
	pod 'Alamofire'
    pod 'FSCalendar'
    pod 'DCPathButton'
    pod 'RAMAnimatedTabBarController'

end
